num partitions Parameter for rdd_of_rasters
geotrellis/geopyspark-netcdf pull request #20
Opened 2017-11-07 18:55 UTC by jbouffard

This PR adds the `num_partitions` parameter to the `rdd_of_rasters` method. This will allow users to input the desired number of partitions more easily.

This PR resolves #19

2017-11-13 14:46 UTC, echeipesh requested changes

2017-11-13 14:46 UTC, echeipesh commented on backend/gddp/src/main/scala/Gddp.scala
> +        case null => sc.defaultMinPartitions
I've always used `defaultParallelism` for this purpose. I'm not familiar with `defaultMinPartitions` but the docs say:
"Notice that we use math.min so the "defaultMinPartitions" cannot be higher than 2." I'm not sure when that is helpful.

2017-11-14 16:59 UTC, jbouffard commented on backend/gddp/src/main/scala/Gddp.scala
> +        case null => sc.defaultMinPartitions
Yeah, I'm not really sure why I chose `defaultMinPartitions` over `defaultParallelism`. I'm going to change that now.

2017-11-14 17:16 UTC, echeipesh approved these changes

2017-11-16 03:55 UTC, merged